---
- name: Deploying Kong
  become: true
  hosts: webservers
  tasks:
    - name: Apt update
      command: "sudo apt update"

    - name: Install Python Dependecies
      apt:
        name: software-properties-common
        state: present

    - name: Install Python3
      apt:
        name: python3
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create network
      docker_network:
        name: kong-net
        driver: bridge

    - name: Start database
      docker_container:
        name: kong-database
        image: postgres:14
        restart_policy: always
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_PASSWORD: kong
        networks:
          - name: kong-net
        volumes:
          - /home/opc/postgres:/usr/data
        ports:
          - "5432:5432"
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "kong"]
          interval: 5s
          timeout: 5s
          retries: 5

    - name: Start Kong migrations
      docker_container:
        name: kong-migration
        image: kong/kong-gateway:3.0.2.0-debian
        command: "kong migrations bootstrap"
        restart_policy: on-failure
        env:
          KONG_DATABASE: postgres
          KONG_PG_HOST: kong-database
          KONG_PG_USER: kong
          KONG_PG_PASSWORD: kong
          KONG_PG_DATABASE: kong
        networks:
          - name: kong-net
        links:
          - kong-database
        #depends_on:
        #  - kong-database

    - name: Start Kong control plane
      docker_container:
        name: kong-controlplane
        image: kong/kong-gateway:3.0.2.0-debian
        restart_policy: on-failure
        env:
          KONG_ROLE: control_plane
          KONG_CLUSTER_CERT: /cert/cluster.crt
          KONG_CLUSTER_CERT_KEY: /cert/cluster.key
          KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
          KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8445 ssl
          KONG_DATABASE: postgres
          KONG_PG_HOST: kong-database
          KONG_PG_USER: kong
          KONG_PROXY_LISTEN: "off"
          KONG_STREAM_LISTEN: "off"
          KONG_PG_PASSWORD: kong
          KONG_PG_DATABASE: kong
          KONG_ADMIN_SSL_CERT: /cert/starocidevparts/star.oci-dev.parts.tvh.com-chain.crt
          KONG_ADMIN_SSL_CERT_KEY: /cert/starocidevparts/star.oci-dev.parts.tvh.com.key
          KONG_ADMIN_GUI_SSL_CERT: /cert/starocidevparts/star.oci-dev.parts.tvh.com-chain.crt
          KONG_ADMIN_GUI_SSL_CERT_KEY: /cert/starocidevparts/star.oci-dev.parts.tvh.com.key
          KONG_ADMIN_API_URI: https://kong-manager-api.oci-dev.parts.tvh.com:8444
          KONG_ADMIN_GUI_URL: https://kong-manager.oci-dev.parts.tvh.com:8445
          KONG_LICENSE_PATH: /kongenterprise/license.json
          KONG_CLUSTER_LISTEN: 0.0.0.0:8005 ssl
          KONG_CLUSTER_TELEMETRY_LISTEN: 0.0.0.0:8006 ssl
        networks:
          - name: kong-net
        volumes:
          - /cert:/cert
          - /kongenterprise:/kongenterprise
        #depends_on:
        #  - kong-migration
        #  - kong-database
        healthcheck:
          test: ["CMD", "kong", "health"]
          interval: 10s
          timeout: 10s
          retries: 5
        ports:
          - "8001:8001"
          - "8444:8444"
          - "8002:8002"
          - "8445:8445"
          - "8003:8003"
          - "8004:8004"
          - "8005:8005"
          - "8006:8006"

    - name: Start Kong data plane
      docker_container:
        name: kong-dataplane
        image: kong/kong-gateway:3.0.2.0-debian
        networks:
          - name: kong-net
        volumes:
          - /cert:/cert
        restart_policy: always
        env:
          KONG_ROLE: data_plane
          KONG_CLUSTER_CONTROL_PLANE: kong-controlplane.:8005
          KONG_CLUSTER_TELEMETRY_ENDPOINT: kong-controlplane.:8006
          KONG_KONG_TRUSTED_IPS: 0.0.0.0/0,::0
          KONG_DATABASE: "off"
          KONG_ADMIN_LISTEN: "off"
          KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
          KONG_SSL: "on"
          KONG_SSL_CERT: /cert/starapiocidev/star.api.oci-dev.parts.tvh.com-chain.crt
          KONG_SSL_CERT_KEY: /cert/starapiocidev/star.api.oci-dev.parts.tvh.com.key
          KONG_CLUSTER_CERT: /cert/cluster.crt
          KONG_CLUSTER_CERT_KEY: /cert/cluster.key
          KONG_LUA_SSL_TRUSTED_CERTIFICATE: /cert/cluster.crt
        #depends_on:
        #  - name: kong-controlplane
        ports:
          - "8000:8000"
          - "8443:8443"
          - "443:443"
